#!/usr/bin/env python3

import requests
from bs4 import BeautifulSoup

url = "https://www.humblebundle.com/books/unfck-your-life-microcosm-books"
resp = requests.get(url)

# print(resp.text)

soup = BeautifulSoup(resp.text, 'html.parser')
bdi = soup.select('.dd-header-headline')
print(bdi)
# print(bdi[1])
# print(bdi[1].text.strip())

for x in bdi:
    print(x.text.strip())
