#!/usr/bin/env python3

import requests
from bs4 import BeautifulSoup

url = "https://www.humblebundle.com/books/unfck-your-life-microcosm-books"
resp = requests.get(url)

soup = BeautifulSoup(resp.text, 'html.parser')

# bundle Tiers
# .dd-header-headline
tier_headlines = soup.select('.dd-header-headline')

stripped_tiernames = [tier.text.strip() for tier in tier_headlines]
print(stripped_tiernames)


# this is datastructure to store budle info
#tiers = {
#    "tier1": {
#        "price": 500,
#        "products": [
#            "name1",
#            "name2",
#        ]
#    },
#    "tier2": {
#            "price": 500,
#            "products": [
#                "name1",
#                "name2",
#            ]
#        }
#}
# common access pattern
#for tiername,tierinfo in tiers.items():
#    print(tiername)
#    print("priced at", tierinfo['price'])
#    print("products:")
#    print(", ".join(tierinfo['products']))
#    print("\n\n")


