#!/usr/bin/env python3

import requests
from bs4 import BeautifulSoup

url = "https://tie-house.com/product-category/suit/" 
resp = requests.get(url)

#print(resp.text)

soup = BeautifulSoup(resp.text,'html.parser')
bdi = soup.select('span.woocommerce-Price-amount amount')
print(bdi[1])
print(bdi[1].text.strip())

for x in bdi:
    print(x.text.strip())

